/**
 * This controller exists to create an exception for testing
 */

const intentionalErrorController = {};

intentionalErrorController.causeError = async function (req, res, next) {
    console.log("Intentional error triggered (causeError).");
    // The render templates expect data that is not being provided. This will also cause an exception.
  throw new Error("This is an intentional error generated by causeError().");
};

// Route:trigger-error
intentionalErrorController.throwError = (req, res, next) => {
  console.log("Intentional error triggered (throwError).");
  throw new Error("Intentional test error triggered by throwError().");
};

module.exports = intentionalErrorController;